# Stockfish Configuration
stockfish.path=/opt/homebrew/bin/stockfish
stockfish.threads=2
stockfish.hash=64

# Lichess API Configuration

# Game Configuration
game.default.duration=10
game.default.increment=0
